version: 0.7.0-{build}

image:
- Visual Studio 2015
- Ubuntu1804

environment:
  matrix:
    - BITS: 64
    - BITS: 32

matrix:
  exclude:
    - image: Ubuntu1804
      BITS: 32

install:
  - cmd: IF "%BITS%" == "32" SET ARCH=i686
  - cmd: IF "%BITS%" == "64" SET ARCH=x86_64
  - cmd: SET PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - cmd: >
      pacman --noconfirm -S
      mingw-w64-%ARCH%-{meson,SDL2,SDL2_mixer,SDL2_image,freetype,glew}
  - sh: sudo apt-get -y update
  - sh: >
      sudo apt-get -y install libsdl2-mixer-dev libsdl2-image-dev
      libsdl2-dev meson ninja-build libfreetype6-dev libglew-dev

build_script:
  - pwd
  - mkdir build
  - cd build
  - meson ..
  - ninja

test: false
